name: native_bridge
description: Custom utility native bridge
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    lint: ^1.5.3

flutter:
    plugin:
        platforms:
            windows:
                pluginClass: NativeBridgePlugin
