name: extensions
description: Extensions system of Yukino
version: 0.0.15

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    crypto: ^3.0.1
    encrypt: ^5.0.0
    flutter:
        sdk: flutter
    fuzzy: ^0.4.0-nullsafety.0
    hetu_script: ^0.1.2+5
    html: ^0.15.0
    http: ^0.13.3
    utilx:
        git:
            url: https://github.com/yukino-app/yukino.git
            path: packages/utilx

dev_dependencies:
    lint: ^1.5.3
