name: iOS (Ipa)

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm

            - uses: subosito/flutter-action@v1.5.3
              with:
                  channel: master

            - name: 🚧 Do prerequisites
              run: |
                  flutter pub get
                  npm ci
                  npm run hive:generate

            - name: 🔨 Building ipa
              run: npm run ios:build

            - name: 🚀 Upload ipa
              uses: actions/upload-artifact@v2
              with:
                  name: ios-ipa
                  path: build/packed/ios/*.ipa
                  if-no-files-found: error
