name: MacOS (Dmg)

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: npm

            - uses: subosito/flutter-action@v1.5.3
              with:
                  channel: beta

            - name: 🚧 Do prerequisites
              run: |
                  brew install create-dmg
                  flutter config --enable-macos-desktop
                  flutter pub get
                  npm ci
                  npm run hive:generate

            - name: 🔨 Building binaries
              run: npm run macos:build

            - name: 📦 Packing as dmg
              run: npm run macos:build:dmg

            - name: 🚀 Upload dmg
              uses: actions/upload-artifact@v2
              with:
                  name: macos-dmg
                  path: build/packed/macos/*.dmg
                  if-no-files-found: error
