name: Windows (Zip & Installer)

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: npm

            - uses: subosito/flutter-action@v1.5.3
              with:
                  channel: master

            - name: 🚧 Do prerequisites
              run: |
                  flutter config --enable-windows-desktop
                  flutter pub get
                  npm ci
                  npm run hive:generate

            - name: 🚩 Check for existing releases
              run: npm run check-release -- --ends " - windows.zip" " - windows.exe"

            - name: 🔨 Building binaries
              run: npm run windows:build

            - name: 📦 Packing as zip
              run: npm run windows:build:zip

            - name: 📦 Packing as installer
              run: npm run windows:build:installer

            - name: 🔢 Get version
              run: |
                  const { spawn, promisifyChildProcess } = require("./cli/spawn");
                  await spawn("npm", ["run", "helpers:version:print", "-s"]);

            - name: 🚀 Release zip and exe
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  name: v${{ env.APP_VERSION }}
                  tag: v${{ env.APP_VERSION }}
                  artifacts: "build/packed/windows/* - windows.{exe,zip}"
                  draft: true
                  token: ${{ secrets.GITHUB_TOKEN }}
